name: CI Pipeline (Testing)

# Trigger: Whenever code is pushed or a pull request is created
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Frontend Tests (Angular)
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # IMPORTANT: Tell GitHub to go into the frontend directory
    steps:
      # 1. Download code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Node.js (with caching for faster builds!)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # IMPORTANT: Adjust this to your Node.js version 
          cache-dependency-path: ./frontend/package-lock.json

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm ci

       # Run tests + generate coverage report
      - name: Run Angular Tests with Coverage
        run: npx ng test --watch=false --browsers=ChromeHeadless --no-progress --code-coverage

      # Upload Coverage Report as Artifact (So that it can be downloaded in GitHub)
      - name: Upload Coverage Report
        if: always() # Also runs when tests fail
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: ./frontend/coverage/
          retention-days: 7  # Keep these uploaded files for 7 days, and then automatically delete them to free up storage space.